import { Analyst } from './types';

export const analysts: Analyst[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    title: 'Senior Technology Analyst',
    bio: 'Specialized in enterprise software and cloud infrastructure with 12+ years of experience. Former VP of Research at Goldman Sachs.',
    expertise: ['Cloud Infrastructure', 'SaaS', 'Enterprise Software', 'Cybersecurity'],
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 247,
    hourlyRate: 350,
    responseTime: '2 hours',
    location: 'San Francisco, CA',
    verified: true,
    followers: 8420,
  },
  {
    id: '2',
    name: 'Marcus Williams',
    title: 'Healthcare & Biotech Analyst',
    bio: 'Focused on pharmaceutical innovation and medical device companies. PhD in Molecular Biology from Stanford.',
    expertise: ['Biotech', 'Pharmaceuticals', 'Medical Devices', 'Clinical Trials'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 189,
    hourlyRate: 300,
    responseTime: '4 hours',
    location: 'Boston, MA',
    verified: true,
    followers: 6340,
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    title: 'Financial Services Analyst',
    bio: 'Expert in fintech disruption, banking regulations, and alternative assets. 10 years at Morgan Stanley.',
    expertise: ['Fintech', 'Banking', 'Crypto', 'Payments'],
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 156,
    hourlyRate: 320,
    responseTime: '3 hours',
    location: 'New York, NY',
    verified: true,
    followers: 5210,
  },
  {
    id: '4',
    name: 'David Park',
    title: 'Energy & Sustainability Analyst',
    bio: 'Deep expertise in renewable energy transition and carbon markets. MBA from MIT Sloan.',
    expertise: ['Renewables', 'Battery Tech', 'Carbon Credits', 'Energy Storage'],
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    rating: 4.6,
    reviews: 134,
    hourlyRate: 280,
    responseTime: '5 hours',
    location: 'Seattle, WA',
    verified: true,
    followers: 4890,
  },
  {
    id: '5',
    name: 'Jessica Thompson',
    title: 'Consumer & Retail Analyst',
    bio: 'Specializing in e-commerce trends, consumer behavior, and retail disruption. Former strategy consultant at McKinsey.',
    expertise: ['E-commerce', 'CPG', 'Fashion Tech', 'Supply Chain'],
    image: 'https://images.unsplash.com/photo-1532074205216-d0e67c941df2?w=400&h=400&fit=crop',
    rating: 4.8,
    reviews: 201,
    hourlyRate: 290,
    responseTime: '2 hours',
    location: 'Austin, TX',
    verified: true,
    followers: 7120,
  },
  {
    id: '6',
    name: 'Robert Chang',
    title: 'Industrial & Manufacturing Analyst',
    bio: 'Focused on automation, robotics, and industrial IoT. 15 years in operations and supply chain.',
    expertise: ['Automation', 'Robotics', 'Industrial IoT', 'Manufacturing'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    rating: 4.5,
    reviews: 98,
    hourlyRate: 270,
    responseTime: '6 hours',
    location: 'Detroit, MI',
    verified: true,
    followers: 3450,
  },
  {
    id: '7',
    name: 'Sophia Patel',
    title: 'AI & Machine Learning Analyst',
    bio: 'Expert in generative AI, LLMs, and AI infrastructure. Previously led AI research at DeepMind.',
    expertise: ['Generative AI', 'Machine Learning', 'LLMs', 'AI Infrastructure'],
    image: 'https://images.unsplash.com/photo-1517841905240-111ab144d141?w=400&h=400&fit=crop',
    rating: 4.9,
    reviews: 312,
    hourlyRate: 380,
    responseTime: '1 hour',
    location: 'Palo Alto, CA',
    verified: true,
    followers: 12850,
  },
  {
    id: '8',
    name: 'James Mitchell',
    title: 'Real Estate & Infrastructure Analyst',
    bio: 'Specializing in commercial real estate, smart cities, and infrastructure investments.',
    expertise: ['Commercial Real Estate', 'Smart Cities', 'PropTech', 'Infrastructure'],
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    rating: 4.7,
    reviews: 167,
    hourlyRate: 310,
    responseTime: '3 hours',
    location: 'Los Angeles, CA',
    verified: true,
    followers: 5680,
  },
];
